# ------------------------------
# - logging
# ------------------------------

logging:
  level.org.springframework.web: ERROR
  level.org.hibernate: ERROR
  file: rvep.spring.log

# ------------------------------
# - enable remote debug
# ------------------------------

spring.devtools.remote.secret: mysecret

# ------------------------------
# - datasource / jpa / hibernate
# ------------------------------

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/rvep
  username: rvep
  password: password

spring.jpa:
  hibernate:
    ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  properties:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.show_sql: false
    hibernate.format_sql: true
    hibernate.hbm2ddl.auto: update
    hibernate.apply_to_ddl: false
    hibernate.connection.CharSet: UTF-8
    hibernate.connection.useUnicode: true

# ------------------------------
# - firebase
# ------------------------------

firebase:
  project_info:
    project_number: 514116175895
    firebase_url: https://rvep-dev.firebaseio.com
    project_id: rvep-dev
    storage_bucket: rvep-dev.appspot.com

  client:
    oauth_client:
        client_id: 820006897104-060cdi3i1kj99ltb22adh8e017a7mel3.apps.googleusercontent.com
    api_key:
        current_key: dxRWH55iSv3SK3rb3demxI8U